// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/omg-electric-header/Current.tsx": () => import("../components/mockups/omg-electric-header/Current.tsx"),
  "./components/mockups/omg-electric-header/Electric.tsx": () => import("../components/mockups/omg-electric-header/Electric.tsx")
};
